library(shiny)



ui <- fluidPage(
  titlePanel("Mean Arterial Pressure and Pulse Pressure "),
  h4("Mean arterial pressure is average blood pressure of a person during a single cardiac cycle when blood is pumped from the ventricle into the arteries."),

  h4("Pulse pressure is difference between the systolic and diastolic pressures and could be translated as the force generated by each of the heart contractions. In the case of resting blood pressure PP is around 40mmHg."),
  sidebarLayout(
    sidebarPanel(
        numericInput("SP", label = strong("Systolic pressure (SP):*"), 115, min = 10, max = 250,), 
        br(),
        numericInput("DP", label = strong("Diastolic pressure (DP):*"), 70, min = 50, max = 200,),
        br(),
        actionButton("calculate", label = "Calculate")),
                  
    mainPanel(
                    h3("Your Mean Arterial Pressure is :"),
                    h2(textOutput("map_result")),
                    h3("Your Pulse Pressure is :"),
                    h2(textOutput("pp_result")),
                    h3("Your blood presure Status is :"),
                    h2(textOutput("status")),
                    
    ))
  )





server <- function(input, output) {
  values <- reactiveValues()
  observe({
    input$calculate
    values$map <- isolate({
      (((2*input$DP) + input$SP)/3)
      })
    values$pp <- isolate({
      (input$SP - input$DP)
    })
    
  })
  
  output$status <- renderText({
    if(input$calculate == 0) "" else {
      if (input$SP<120 && input$DP<80){
        values$status = "Normal Blood Pressure"
      }
      else if (input$SP<139 && input$DP<89){
        values$status ="Pre-hypertension"
      }
      else if (input$SP<159 && input$DP<99){
        values$status ="Stage I High Blood Pressure (Hypertension)"
      }
      else if (input$SP<180 && input$DP<110){
        values$status ="Stage II High Blood Pressure (Hypertension)"
      }
      else{
        values$status ="Hypertensive crisis, emergency care is required.)"
      }
      paste("", values$status)
    }
  })
  output$map_result <- renderText({
    if(input$calculate == 0) "" else
      paste("", values$map)
  })
  
  output$pp_result <- renderText({
    if(input$calculate == 0) "" else
      paste("", values$pp)
  })
}






shinyApp(ui = ui, server = server)